### ISSUE TITLE
Update app.yaml for GCloud CLI

### ISSUE THREAD

**Issue by PatrickVienne** [smartninja/wd2-boilerplate#1]
app.yaml has to be updated for `gcloud`

It will work with this:
```yaml
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
```
